# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker compose up -d'.

version: "3.4"
services:
  broker:
    container_name: redis
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /mnt/volume_01/redisdata:/data


  webserver:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8001:8000"
    volumes:
      - /mnt/volume_01/data:/usr/src/paperless/data
      - /mnt/volume_01/media:/usr/src/paperless/media
      - /mnt/volume_01/export:/usr/src/paperless/export
      - /mnt/volume_01/consume:/usr/src/paperless/consume
      # - data:/usr/src/paperless/data
      # - media:/usr/src/paperless/media
      # - ./export:/usr/src/paperless/export
      # - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: 10.108.0.2:5432
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    container_name: gotenberg
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    container_name: tika
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata:
