version: '3.3'

services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - /mnt/volume_01/wp_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: 10.108.0.2:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
