version: '3.1'

services:
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - "3306:3306"
    volumes:
      - /mnt/volume_01/wp_db_data:/var/lib/mysql
